# Generated by Django 4.1.4 on 2023-01-28 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_products_options_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='count',
            new_name='order_count',
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 17, 8, 47, 115721)),
        ),
    ]
