# Generated by Django 4.1.4 on 2023-01-28 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_rename_count_orders_order_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 17, 11, 48, 870944)),
        ),
    ]
