# Generated by Django 4.1.4 on 2023-02-05 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_ticket_available_ticket_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 12, 15, 25, 968239)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
