# Generated by Django 4.1.4 on 2023-02-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobby',
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.SmallIntegerField(null=True),
        ),
    ]
